### ISSUE TITLE
problem running Rtoolbox

### ISSUE THREAD

**Issue by duyphamuab** [PeeperLab/Rtoolbox#1]
Hi,
I used your script and I almost got what I want. However, the color bar (below the plot) only showed blue. Can you help? I attached the output from preranked GSEA ( I generated this using .rnk and .gmx file). 

[example.zip](https://github.com/PeeperLab/Rtoolbox/files/1062601/example.zip)

**Comment by thomasKuilman** [comment]
You are right; there is a bug in the script that causes this. Thanks for the feedback; will try to fix this asap and let you know.

Thomas

**Comment by thomasKuilman** [comment]
I  realized that everything should work properly but the problem is that your ranking metric has a range of -2.75e+18 to 1.85e+33. The script normalizes based on the min and max values, but these are so big that all values become the same (hence the blue bar). In all honesty, the range of your ranking metric does not seem to make a lot of sense; can you not use a log-transformed ranking metric value? That would solve all your problems (as ling as you are using the updated version of Rtoolbox (1.6)

**Comment by duyphamuab** [comment]
Thanks! That solved the problem.

**Comment by imcoleman** [comment]
Hello,
I also had this issue of the metric color scale not displaying properly, even though my metric was in the range of (-33 to 64.) It displays correctly using the java gsea program. Would you mind checking my example?

I also had trouble saving the plot. I tried this:
geneset <- "BELTRAN_UP_29"
png(file=file.path(outputpath,paste(geneset,".png",sep="_")), width = 3*300,height = 3*300, res=300)	
replotGSEA(path=datapath, gene.set=geneset, class.name="Bromedemstat")
dev.off()

I also tried the above with print(replotGSEA(path=datapath, gene.set=geneset, class.name="Bromedemstat")) but the plot only renders in the console. An example for saving to file would be much appreciated.

Thanks!

[example2.zip](https://github.com/PeeperLab/Rtoolbox/files/8454559/example2.zip)
