### ISSUE TITLE
Metric color display incorrect

### ISSUE THREAD

**Issue by imcoleman** [PeeperLab/Rtoolbox#6]
Hello,
I have an issue of the metric color scale not displaying properly, even though my metric was in the range of (-33 to 64.) It displays correctly using the java gsea program. Would you mind checking my example?

I also had trouble saving the plot. I tried this:
geneset <- "BELTRAN_UP_29"
png(file=file.path(outputpath,paste(geneset,".png",sep="_")), width = 3300,height = 3300, res=300)
replotGSEA(path=datapath, gene.set=geneset, class.name="Bromedemstat")
dev.off()

I also tried the above with print(replotGSEA(path=datapath, gene.set=geneset, class.name="Bromedemstat")) but the plot only renders in the console. An example for saving to file would be much appreciated.

Thanks!
[example2.zip](https://github.com/PeeperLab/Rtoolbox/files/8573569/example2.zip)

**Comment by thomasKuilman** [comment]
The color scale is in the same range as the ranking metric plot, defaulting to the range you mention. Since this is not centered around 0, the colors are 'shifted'. You can solve this using:

`replotGSEA(path="~/Downloads/example2/", gene.set=geneset, class.name="Bromedemstat", metric.range = c(-64, 64))`

<img width="382" alt="Screenshot 2022-06-28 at 21 24 06" src="https://user-images.githubusercontent.com/8489622/176270428-2e56fbd0-7e86-487d-953e-d72e5fb41c19.png">
